Controllers/VirtualEstudianteController.cs
using GestionCalificaciones.Models;
using GestionCalificaciones.Services.Asignatura;
using GestionCalificaciones.ViewModel.CalificacionesEstudiante;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace GestionCalificaciones.Controllers
{
    [Authorize]
    [Authorize(Roles = "ESTUDIANTES")]
    public class VirtualEstudianteController : Controller
    {
        
        // GET: VirtualEstudiante
        GestionCalificacionDBEntities1 _db;
        string SrtrinRutaDirecion;
        public VirtualEstudianteController()
        {
            _db = new GestionCalificacionDBEntities1();
        }
        public ActionResult Index()
        {
            var serEst = new Services.Estudiantes.EstudiantesModelService();
            var user = int.Parse(Roles.GetRolesForUser()[0]);
            var DatosPerfil = serEst.GetSelectWhere(user);
            ViewBag.DatosPerfil = DatosPerfil;
            string NombreFotoPerfil = DatosPerfil.PrimerNombre + " " + DatosPerfil.PrimerApellido;
            NombreFotoPerfil = NombreFotoPerfil.Trim(new Char[] { '=' });

            ViewBag.FotoPerfil = NombreFotoPerfil;
            return View();
        }

        public ActionResult Calificaciones()
        {
            ViewBag.semestreSelected = null;
            var listCalEstudiante = new List<CalificacionesEstudianteViewModel>();

            var CalificaciconesEstudiante = _db.spes_Calificaciones(Roles.GetRolesForUser()[2], null).ToList();
            var list = new List<int>();
            list.Add(2);
            ViewBag.listSemestre = ToSelectList(list).Prepend(new SelectListItem { Value = null, Text = "Seleccionar" });

            string FirstViewSemestre = Constantes.Constantes.Valores.SEMESTRE_ACTUAL.ToString();
            foreach (var data in CalificaciconesEstudiante)
            {
                string asignaturaNombre = new AsignaturaModelService().GetSelectWhereNameAsignatura(data.materia.ToString()).AsignaturaNom;
                var calEstudiante = new CalificacionesEstudianteViewModel();
                calEstudiante.parcial = data.parcial;
                calEstudiante.practica = data.practica;
                calEstudiante.final = data.final;
                calEstudiante.NotaLiteral = data.NL;
                calEstudiante.total = data.total;
                calEstudiante.Asignatura = asignaturaNombre;
                calEstudiante.Materia = data.materia.ToString();
                listCalEstudiante.Add(calEstudiante);
            }
            listCalEstudiante.ForEach(s => s.semestreSelected = FirstViewSemestre);
            return View(listCalEstudiante);
        }

        private SelectList ToSelectList(List<int> semestreList)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (var data in semestreList)
            {
                list.Add(new SelectListItem()
                {
                    Text = data.ToString(),
                    Value = data.ToString()
                });
            }

            return new SelectList(list, "Value", "Text");
        }
        [HttpPost]
        public ActionResult getCalificacionesBySemestre(string semestreSelected)
        {

            int? semestre;
            int sem;
            if (int.TryParse(semestreSelected, out sem))
                semestre = sem;
            else
                semestre = null;

            ViewBag.semestreSelected = Constantes.Constantes.Valores.SEMESTRE_ACTUAL;
            var CalificaciconesEstudiante = _db.spes_Calificaciones(Roles.GetRolesForUser()[2], Constantes.Constantes.Valores.SEMESTRE_ACTUAL).ToList();

            var listCalEstudiante = new List<CalificacionesEstudianteViewModel>();

            var SemestresCursadoSP = new List<int>();
            SemestresCursadoSP.Add(2);
            ViewBag.listSemestre = ToSelectList(SemestresCursadoSP).Append(new SelectListItem { Value = null, Text = "Seleccionar" });

            string FirstViewSemestre = "ENERO - ABRIL 2022";
            foreach (var data in CalificaciconesEstudiante)
            {
                string asignaturaNombre = new AsignaturaModelService().GetSelectWhereNameAsignatura(data.materia.ToString()).AsignaturaNom;
                var calEstudiante = new CalificacionesEstudianteViewModel();
                calEstudiante.parcial = data.parcial;
                calEstudiante.practica = data.practica;
                calEstudiante.final = data.final;
                calEstudiante.NotaLiteral = data.NL;
                calEstudiante.total = data.total;
                calEstudiante.Asignatura = asignaturaNombre;
                calEstudiante.Materia = data.materia.ToString();
                listCalEstudiante.Add(calEstudiante);
            }
            listCalEstudiante.ForEach(s => s.semestreSelected = semestreSelected);
            return PartialView("_CalificacionesVisualizacion", listCalEstudiante);
        }
    }
}

Views/VirtualEstudiante/Calificaciones.cshtml
@model List<GestionCalificaciones.ViewModel.CalificacionesEstudiante.CalificacionesEstudianteViewModel>
@{
    ViewBag.Title = "Calificaciones";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}


<div class="card p-3">
    <nav>
        <h3 class="pr-5 text-center ">Calificaciones</h3>
    </nav>
    <hr />
    <div class="form-row">
        <div class="col-4">
            <label for="semestreDropDown">Cuatrimestre</label>
            @Html.DropDownListFor(m => m.FirstOrDefault().semestreSelected, ViewBag.listSemestre as IEnumerable<SelectListItem>,
    new
        {
            @class = "custom-select custom-select-lg",
            @id = "semestreDropDown"
    })
        </div>
        <span id="textLoading" class="font-weight-bold text-uppercase text-center text-primary"></span>
    </div>

    @Html.Partial("_CalificacionesVisualizacion", Model)
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $(document).on("change", "#semestreDropDown", function (e) {
                var val = $('#semestreDropDown option:selected').val();
                ModalLoading();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("getCalificacionesBySemestre", "VirtualEstudiante")',
                    data: { semestreSelected: val},
                    success: function successFunc(data) {
                        $("#partialCalificaciones").replaceWith(data);
                    },
                    error: function errorFunc() {
                        alert('error');
                    },
                    complete: function () {
                        ModalLoadingFinished();
                    }
                });
                e.stopImmediatePropagation();
            });
        });

        function ModalLoading() {
            $("#textLoading").text("Cargando...");
        }

        function ModalLoadingFinished() {
            $("#textLoading").text("");
        }
    </script>
}

Views/VirtualEstudiante/Index.cshtml
<div>
    @{
        Layout = "~/Views/Shared/_LayoutMenu.cshtml";
    }

    @*<hr /> *@

    <div class="card" style="background-image: linear-gradient(15deg, #5b6be8 30%, #00B4D8 70%); color: black;
        padding: 2em;">
        <div class="row">
            <div class="col-3">
                <div class="p-5">
                    <center>
                        <object data="~/imagen/user/@ViewBag.FotoPerfil-.jpg" style="border-radius:100%;width:200px" type="image/png">
                            <img src="https://image.flaticon.com/icons/png/512/149/149071.png" width="200" class="img-circle">
                        </object>
                    </center>
                </div>
                <div class="text-center">
                    <h5>
                        <a href="~/VirtualEmpleado/CambiarFoto">Cambiar foto de perfil</a>
                    </h5>
                </div>
            </div>
            <div class="col-9">



                <div class="row ">
                    <div class="col-sm-10">
                        <div class="form-group">
                            <p class="form-control-static display-4">@ViewBag.DatosPerfil.PrimerNombre @ViewBag.DatosPerfil.SegundoNombre @ViewBag.DatosPerfil.PrimerApellido @ViewBag.DatosPerfil.SegundoApellido  </p>
                        </div>
                    </div>
                </div>

                <div class="row">

                    <div class="col-6">


                        <div class="row ">
                            <div class="col-sm-10">
                                <div class="form-group">
                                    <p class="form-control-static"><i class="nc-icon nc-single-02"></i>  @('@')@Roles.GetRolesForUser()[2]</p>
                                </div>
                            </div>
                        </div>


                        <div class="row ">
                            <div class="col-sm-10">
                                <div class="form-group">
                                    <p class="form-control-static"><i class="nc-icon nc-email-85"></i>  @ViewBag.DatosPerfil.CorreoElectronico</p>
                                </div>
                            </div>
                        </div>

                        <div class="row ">
                            <div class="col-sm-10">
                                <div class="form-group">
                                    <p class="form-control-static"><i class="nc-icon nc-paper"></i>  @ViewBag.DatosPerfil.FechaNacimiento</p>
                                </div>
                            </div>
                        </div>


                        <div class="row ">
                            <div class="col-sm-10">
                                <div class="form-group">
                                    <p class="form-control-static"><i class="nc-icon nc-world-2"></i>  @ViewBag.DatosPerfil.Direccion</p>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="col-6 pt-5">

                        <div class="row ">
                            <div class="col-sm-10">
                                <div class="form-group">
                                    <p class="form-control-static"><i class="nc-icon nc-mobile"></i> @ViewBag.DatosPerfil.Telefono</p>
                                </div>
                            </div>
                        </div>

                        <div class="row ">
                            <div class="col-sm-10">
                                <div class="form-group">
                                    <p class="form-control-static"><i class="nc-icon nc-mobile"></i> @ViewBag.DatosPerfil.Celular</p>
                                </div>
                            </div>
                        </div>



                        <div class="pt-4 pb-4 pl-3">
                            <h5>
                                <a href="~/VirtualEstudiante/EditarInformacion">Editar información</a>
                            </h5>
                            <h5>
                                @Html.ActionLink("Cambiar contraseña", "CambiarPassword", "VirtualEstudiante")
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>
<div class="modal" id="ModalCondicion" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="titleModalCond"></h5>
            </div>
            <div class="modal-body">
                <p id="txtModalCond"></p>
            </div>
            <div class="modal-footer">
                <a id="botonModalCond1" class="btn btn-success" href="~/VirtualEstudiante/EncuestaSeleccion">Ir a evaluación</a>
                <a id="botonModalCond" class="btn btn-warning active">Entendido</a>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
           
        });
    </script>
}